# Standardized label definitions for moai-adk-go
# Compatible with EndBug/label-sync or manual reference
#
# Usage with EndBug/label-sync:
#   - uses: EndBug/label-sync@v2
#     with:
#       config-file: .github/labels.yml

# --- Type ---
- name: bug
  color: "d73a4a"
  description: "Something is not working"

- name: enhancement
  color: "0075ca"
  description: "New feature or improvement request"

- name: question
  color: "8b5cf6"
  description: "Questions or discussions"

- name: documentation
  color: "0e8a16"
  description: "Documentation improvements"

# --- Priority ---
- name: "priority:critical"
  color: "b60205"
  description: "Critical priority - requires immediate attention"

- name: "priority:high"
  color: "d93f0b"
  description: "High priority - should be addressed soon"

- name: "priority:medium"
  color: "fbca04"
  description: "Medium priority - normal queue"

- name: "priority:low"
  color: "c2c2c2"
  description: "Low priority - when time permits"

# --- Status ---
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "good first issue"
  color: "7ae07a"
  description: "Good for newcomers"

- name: wontfix
  color: "ffffff"
  description: "This will not be worked on"

- name: duplicate
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: stale
  color: "ededed"
  description: "Marked as stale due to inactivity"

- name: pinned
  color: "006b75"
  description: "Pinned and exempt from stale bot"

- name: security
  color: "ee0701"
  description: "Security-related issue"

# --- Scope ---
- name: go
  color: "00add8"
  description: "Go source code changes"

- name: tests
  color: "bfd4f2"
  description: "Test file changes"

- name: docs
  color: "0e8a16"
  description: "Documentation file changes"

- name: ci
  color: "e3d21c"
  description: "CI/CD and GitHub Actions changes"

- name: config
  color: "d4c5f9"
  description: "Configuration file changes (.moai, .claude)"

- name: templates
  color: "c5def5"
  description: "Template file changes"

- name: hooks
  color: "f9d0c4"
  description: "Hook system changes"

# --- AI ---
- name: ai-generated
  color: "0d9488"
  description: "Content generated by AI"

- name: ai-reviewed
  color: "06b6d4"
  description: "Reviewed by AI"

- name: coderabbit
  color: "a5d8ff"
  description: "Reviewed by CodeRabbit"

# --- Dependencies ---
- name: dependencies
  color: "0366d6"
  description: "Dependency updates"
